fernetKey: aERBZE5MN3E0TjRjU2xzQWxCdTNIUks0WGFTZThoWXc=
webserverSecretKey: aERBZE5MN3E0TjRjU2xzQWxCdTNIUks0WGFTZThoWXc=

dags:
  gitSync:
    enabled: true
    repo: https://github.com/CharlesMaponya/Kubernetes-for-DataEngineering.git
    branch: master
    rev: HEAD
    depth: 1
    maxFailures: 0
    subPath: "dags"
    wait: 60
    containerName: git-sync
    uid: 65533
    
# Ensure git-sync only runs where needed
gitSync:
  enabled: true